version: '3.8'
services:
  dev-db:
    image: 'postgres'
    restart: always
    environment:
      POSGRES_USER: postgres
      POSTGRES_DB: slaap
      POSTGRES_PASSWORD: sIrlk46Wlxa73jirI@rO
    logging:
      options:
        max-size: 10m
        max-file: '3'
    networks:
      - slaap-network
    ports:
      - '5434:5432'
    volumes:
      - ./postgres-data:/var/lib/postgres/data
networks:
  slaap-network:
